### ISSUE TITLE
svn:mergeinfo

### ISSUE THREAD

**Issue by gillg** [dsuni/svndumpsanitizer#12]
If you reset your revisions number (with --drop-empty), the properties svn:mergeinfo are not reindexed.
It's a big problem, because if you try to merge a futur revision, which was already merged, the command svn merge do noting !

**Comment by dsuni** [comment]
Is this in the 1.X-series or the new 2.X-series (branch v2)? The 1.X version basically ignores the svn:mergeinfo, but the 2.X at least tries to deal with it. (I say tries because the mergeinfo is a really ugly feature that seems tacked on afterwards.)

2.X is currently at RC3 and I expect to push 1.X into its own no-longer-maintained-branch, and merge 2.X into master before Christmas.
