### ISSUE TITLE
Internal logic error

### ISSUE THREAD

**Issue by Alexhha** [dsuni/svndumpsanitizer#13]
I get the following error
```
# svndumpsanitizer --infile asf-svn.dump --outfile svn-trunk.dump --include subversion/trunk --drop-empty
Reading revision 891326
Tried to add dependency to non-existing parent/revision. 4573 840967 0 subversion/trunk/subversion/tests/libsvn_wc/translate-test.c subversion/trunk/subversion/tests/libsvn_subr/subst-test.c
ERROR: Internal logic error
```

```
# grep -a --text -A20 "Revision-number: 840967" asf-svn.dump
Revision-number: 840967
Prop-content-length: 343
Content-length: 343

K 10
svn:author
V 6
philip
K 8
svn:date
V 27
2002-01-15T02:08:10.101173Z
K 7
svn:log
V 241
* subversion/libsvn_subr/io.c (svn_io_run_cmd): Remove the call to
  apr_procattr_io_set to create pipes, we don't use them. They still
  get created by apr_procattr_child_err_set et.al. but that's an APR
  bug.  Fix text of error messages.

PROPS-END
```

```
# grep -a --text -A17 "Revision-number: 891326" asf-svn.dump
Revision-number: 891326
Prop-content-length: 180
Content-length: 180

K 10
svn:author
V 12
lukaszlenart
K 8
svn:date
V 27
2009-12-16T17:16:51.523206Z
K 7
svn:log
V 72
[maven-release-plugin]  copy for tag struts2-archetype-dbportlet-2.1.8.1
PROPS-END
```

```
# svndumpsanitizer --infile asf-httpd.dump --outfile httpd-trunk.dump --include httpd/httpd/trunk --drop-empty
Reading revision 1651433
Tried to add dependency to non-existing parent/revision. 8861 84778 0 httpd/httpd/branches/avendor/docs/docroot/index.html.ee httpd/httpd/trunk/docs/docroot/index.html.ee
ERROR: Internal logic error
```

The dumps: asf-httpd.dump/asf-svn.dump were made with svnrdump version 1.8.15 (r1718365) from the following urls: https://svn.apache.org/repos/asf/httpd/ and https://svn.apache.org/repos/asf/subversion/

I can restore asf-httpd.dump/asf-svn.dump with ```svnadmin load``` without any problem

```
# svn list http://svn.example.net/repos/svn/subversion/
README
branches/
developer-resources/
site/
site-ng/
svn-logos/
tags/
trunk/
upstream/

# svnlook youngest /svn/repos/subversion/
891327
```

```
# svn list http://svn.example.net/repos/httpd/httpd/
apreq/
docs-build/
flood/
httpd/
mod_fcgid/
mod_ftp/
mod_mbox/
mod_spdy/
mod_wombat/
sandbox/
site/
test/

# svnlook youngest /svn/repos/httpd/
1651434
```

Environment
```
# svndumpsanitizer -v
svndumpsanitizer 2.0.0
```

```
# lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.7 (Final)
Release:        6.7
Codename:       Final
```

```
# gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC)
```

Thanks in advance

**Comment by dsuni** [comment]
It's next to impossible to say what went wrong without access to the dumpfile itself, but one thing seems instantly strange about the error message:

> Tried to add dependency to non-existing parent/revision. 4573 840967 0 subversion/trunk/subversion/tests/libsvn_wc/translate-test.c subversion/trunk/subversion/tests/libsvn_subr/subst-test.c

This error is produced by the "add_file_dep_to_node"-function (the purpose of which is to maintain a dependency between a file created by an svn copy operation and the file it was copied from) The strange part is that the numbers that are printed are (in order) the revision of the node, the revision of the node from which it's copied, as well as the operation (0 == ADD). For this reason the first number should never be smaller than the second, yet in these cases that happens.

In order to do any meaningful debugging I would need access to the dump file - but of course they seem to be quite monstrous...

**Comment by Alexhha** [comment]
> In order to do any meaningful debugging I would need access to the dump file - but of course they seem to be quite monstrous...

Actually it's not so scary :)
``` bash
# du -h asf-svn.dump.xz
98M     asf-svn.dump.xz
```

If it's ok I can share the dump via my personal server (Digital Ocean)

**Comment by dsuni** [comment]
> If it's ok I can share the dump via my personal server (Digital Ocean)

Please do.

**Comment by Alexhha** [comment]
[Here you go](http://storage.sys-adm.org.ua/asf-svn.dump.xz), md5sum: 8f5ac74fe480617519f63907b09cdbdc

**Comment by dsuni** [comment]
Ok. I got it, and I instantly spot a problem:

`SVN-fs-dump-format-version: 3

UUID: 13f79535-47bb-0310-9956-ffa450edef68

Revision-number: 836401`

When you look at the README.md here, you'll see that one of the things svndumpsanitizer does **not** do, is work with partial dump files, so the fact that the first revision is something other than 0, is outside of the expectations, and this explains the error as well.

**Comment by Alexhha** [comment]
Hmm, actually it's not a partial dump. As I understand, asf share one BIG repository across all projects. 
You can look at repo UUID, for svn and httpd they are the same: 
``` bash
# svn info  http://svn.apache.org/repos/asf/subversion/
Path: subversion
URL: http://svn.apache.org/repos/asf/subversion
Relative URL: ^/subversion
Repository Root: http://svn.apache.org/repos/asf
Repository UUID: 13f79535-47bb-0310-9956-ffa450edef68
Revision: 1730186
Node Kind: directory
Last Changed Author: jamessan
Last Changed Rev: 1730032
Last Changed Date: 2016-02-12 14:46:41 +0000 (Fri, 12 Feb 2016)

# svn info  http://svn.apache.org/repos/asf/httpd/
Path: httpd
URL: http://svn.apache.org/repos/asf/httpd
Relative URL: ^/httpd
Repository Root: http://svn.apache.org/repos/asf
Repository UUID: 13f79535-47bb-0310-9956-ffa450edef68
Revision: 1730186
Node Kind: directory
Last Changed Author: rjung
Last Changed Rev: 1730146
Last Changed Date: 2016-02-13 01:52:31 +0000 (Sat, 13 Feb 2016)
```

As for me it's a little bit weird, share one repository for such big projects, but anyway.

So svn project has been started from revision 836401 - http://svn.apache.org/repos/asf/subversion/?p=836401

I have made some test. As workaround

``` bash
# svnadmin dump /svn/repos/subversion/ | svndumpfilter include subversion --drop-all-empty-revs --renumber-revs > svn-local.dump
Including (and dropping empty revisions for) prefixes:
   '/subversion'

* Dumped revision 0.
Revision 0 committed as 0.
* Dumped revision 1.
Revision 1 committed as 1.
* Dumped revision 2.
...
* Dumped revision 20.
* Dumped revision 21.
Revision 20 committed as 2.
Revision 21 committed as 3.
Revision 22 committed as 4.
* Dumped revision 22.
* Dumped revision 23.
Revision 23 committed as 5.
Revision 24 committed as 6.
* Dumped revision 24.
Revision 25 committed as 7.
...
4 => (dropped)
3 => (dropped)
2 => (dropped)
1 => 1
0 => 0
```

``` bash
# svndumpsanitizer --infile svn-local.dump --outfile svn-trunk.dump --include subversion/trunk
Reading revision 78507
Analyzing revision 78507
Writing revision 78507
All done.
```

**Comment by dsuni** [comment]
> Hmm, actually it's not a partial dump. As I understand, asf share one BIG repository across all projects.

Yes, and that big honkin' repository is what svndumpsanitizer considers to be the complete repository. The different parts are just that - parts. The reason it was never made to work with parts, is that there are no guarantees that the different parts of the repository are cleanly separated. The fact that your workaround works means that apparently this time it was. If something at some point had been moved from e.g. httpd/foo to subversion/bar svndumpfilter would have barfed, because you didn't tell it to include anything from httpd.

Svndumpsanitizer was made especially for these messy type situations: It makes no assumptions about "clean separation between projects" or that best practices have been followed (because quite frankly, those project are a tiny minority in the real world); instead it assumes it has **all** the data (= the whole repository starting from revision 0). It will then proceed to analyse the data, and make all decisions based on data rather than assumptions (beyond the one that it has the entire repo).

Anyway, it's good that your workaround worked and you got the repo processed.

**Comment by Alexhha** [comment]
But you know unfortunately I can't restore svn-trunk.dump. I get the following error
```
------- Committed revision 27175 >>>
<<< Started new transaction, based on original revision 27176
svnadmin: E160013: File not found: transaction '27175-kyv', path '/subversion/branches/merge-tracking/notes/incomplete-directories.txt'
     * editing path : subversion/branches/merge-tracking/notes/incomplete-directories.txt ...
```

It's strange, because I have specified --include subversion/trunk that's why it can't find the path subversion/branches/... . But I thought svndumpsanitizer should resolve exactly such issues or did I miss something?

**Comment by dsuni** [comment]
> I thought svndumpsanitizer should resolve exactly such issues or did I miss something?

No, you didn't miss anything. This seems more like a genuine bug. I'll have to investigate...

**Comment by dsuni** [comment]
Ok. This took some time to work out, because
a) I started by importing and re-dumping your file (it's happened more than once that a svndumpsanitizer "bug" has turned out to be a dump file that was broken to begin with, so I always check that first)
b) Debugging with massive files is really slow.
c) There were actually two bugs, rather than one.

They've been fixed now, though, and version 2.0.1 is now released. Please give it a shot.

**Comment by Alexhha** [comment]
Thanks a lot.

Works fine. But After I have restored the dump - I got the following folders
```
# svn ls file:///svn/repos/svn-trunk/subversion/
branches/
site/
tags/
trunk/
upstream/
```

I thought only the trunk folder should be there. Isn't it?

**Comment by dsuni** [comment]
> I thought only the trunk folder should be there. Isn't it?

Not necessarily. Svndumpsanitizer will leave in everything needed to fulfil the historical dependencies of the files under trunk, so if you had a file in branches that was moved to trunk, then that file (and the directories it resides in) will be kept in order to preserve repository integrity.

Basically you can now just delete the things you don't need, and move on (or you can ask svndumpsanitizer to to it for you automatically by providing the --add-delete -option but it really just does the same thing - adds a revision that deletes branches, site, tags and upstream). In version 1 this used to happen automatically, but I noticed that the feature could paper over bugs, so I made it a non-default option, and the default is now that people can check whether it seems sensible.

If you find something in the directories that you think shouldn't be there, you can run svndumpsanitizer with the --query -option, and it will after reading and analysing (but prior to writing) enter an interactive state, where you can query why specific files are being kept.

**Comment by Alexhha** [comment]
I got it. Thanks.
