### ISSUE TITLE
Output dump file broken when it's printed to STDOUT

### ISSUE THREAD

**Issue by dufreyne** [dsuni/svndumpsanitizer#9]
It's correct when printed with -o option

PS. Thank you for the tool, it's unique and works great

**Comment by dsuni** [comment]
I'm unable to reproduce this one. When using my test dump files, the results are identical when svndumpsanitizer is invoked using "-o" or stdout is directed to a file. I would be interested in looking at a diff between two files created in identical ways, but with different ways of output.

Notice that if you just output to the screen, and copy-paste from there the result will be incorrect, because you will get the status messages (printed to stderr) mixed in there as well.

**Comment by dufreyne** [comment]
I compiled the app with VS 2013 under Windows 7, 32-bit
Can this be an issue?

**Comment by dufreyne** [comment]
Just reproduced:
When using STDOUT, dump size 441 481 030 bytes
When using -o, dump size 436 927 750 bytes

**Comment by dsuni** [comment]
It's possible that this is a windows issue -  it wouldn't be the first time it behaved... ehm... in a *special* manner. I really have no clue what it could be, though. Since I don't have a windows machine to test on (and don't want one) I'll probably just document the issue, given that an easy workaround exists.

**Comment by dsuni** [comment]
Thanks for the work. :-)

**Comment by dufreyne** [comment]
My pleasure
